// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let sum = 4000000;
let arr = [1, 2, 3];
for (let i = 3; i <= 35; i++) {
    arr[i] = arr[i-1] + arr[i-2];
    if (arr[i] >= sum) {
        arr.pop()
        break;
    }
}
let result = 0;
for (let i = arr.length; i > 0; i-- ) {
    if(arr[i]%2 ==0) {
        result += arr[i]
    }
}
console.log("Sum of the even-valued terms (lower than 4 milion): "+ result);