// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

// https://sciencerobotics.wordpress.com/2013/11/03/project-euler-problem-12-highly-divisible-triangular-number-javascript-solution/


var number=0;
var n=2;
while(number===0){

    var count = 0;
    var trinum = ( n * (n + 1) ) / 2;

    for(i=1 ; i <= Math.sqrt(trinum) ; i++) {
        if(trinum % i === 0){ //finds multiples, if a multiple is found and it is less than the square root then there is a another one greater than the root
        count += 2;
        }
    }

    if(count > 3){
        number = trinum;
        break;
    }

    n += 1;
    // console.log(count,trinum,n);
}
console.log(number);